services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: 
      context: .
      dockerfile: docker/server.dockerfile    
    container_name: myapp
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://admin:admin@postgres:5432/mydb
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    restart: unless-stopped

  worker:
    build: 
      context: .
      dockerfile: docker/server.dockerfile
    command: celery -A src.core.celery worker --loglevel=info
    depends_on:
      - rabbitmq
      - app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

volumes:
  postgres_data: