services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: docker/server.dockerfile    
    container_name: myapp
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://admin:admin@postgres:5432/mydb
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: